name: itotko
recipe: drupal9
config:
  webroot: web
  php: 7.3
  database: mariadb
  xdebug: true

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=PHPSTORM"
        DRUSH_OPTIONS_URI: "http://itotko.lndo.site"
        XDEBUG_CONFIG: "remote_enable=true remote_host=10.254.254.254 xdebug.remote_port=9000 xdebug.remote_log='/tmp/xdebug.log' xdebug.max_nesting_level=1500"
  database:
    type: mariadb
    portforward: true
  memcached:
    type: memcached
    portforward: true
  node:
    type: node:16

tooling:
  build-stylesheet:
    description: Rebuild the css file from the scss file
    cmd:
      - node: rm -rf /app/web/themes/custom/itotko_thtme/css
      - node: sass /app/web/themes/custom/itotko_theme/scss/style.scss /app/web/themes/custom/itotko_theme/css/style.css

  pre-import:
    description: Build local dependencies, import config and run database updates
    cmd:
      - appserver: drush site:install --db-url=mysql://drupal9:drupal9@database/drupal9 --account-pass=content --site-name=$LANDO_APP_NAME -y
      - appserver: /bin/sh -c "chmod -R u+rw web/sites"
      - appserver: echo "# IMPORT files and DB next >>>>>>>>"

  post-import:
    description: Imports config and run database updates
    cmd:
      - appserver: drush then bootstrap5 -y
      - node: npm --prefix /app/web/themes/contrib/bootstrap5 install
      - node: npm install -g sass
      - node: sass /app/web/themes/custom/itotko_theme/scss/style.scss /app/web/themes/custom/itotko_theme/css/style.css
      - appserver: drush updb -y
      - appserver: drush cim --source=../config -y
      - appserver: drush cr
