services:
  www:
    build:
      dockerfile: docker/Dockerfile
    environment:
      USERNAME: itotko
      PASSWORD: passwordforitotko
      HOST: db
      DB: itotko
      DOMAINNAME: itotko.dk
      WWWDOMAINNAME: www.itotko.dk
      APACHE_DOCUMENT_ROOT: /var/www/html
      MEMCACHED_SERVER: memcached
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - drupal_files:/var/www/html/web/sites/default/files
      - ./config:/var/www/config
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true
      memcached:
        condition: service_started
  db:
    image: mariadb:10
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_ROOT_PASSWORD: rootitotko
      MARIADB_USER: itotko
      MARIADB_PASSWORD: passwordforitotko
      MARIADB_DATABASE: itotko
  memcached:
    image: memcached:1.6.33
    restart: unless-stopped
volumes:
  db_data:
  drupal_files:
