#!/bin/bash
set -e

sed -i "s|@MEMCACHED_SERVER@|$MEMCACHED_SERVER|" \
    /var/www/web/sites/default/settings.php

sed -i "s|@WWWDOMAINNAME@|$WWWDOMAINNAME|" \
    /var/www/web/sites/default/settings.php

sed -i "s|@DOMAINNAME@|$DOMAINNAME|" \
    /var/www/web/sites/default/settings.php

cd /var/www || return

# Insert the database settings into settings.php.
vendor/bin/drupal dba --password=$PASSWORD --driver=mysql --host=$HOST --database=$DB \
--username=$USERNAME --port=3306 --default -n

vendor/bin/drush updb -y
vendor/bin/drush cr

/usr/local/bin/apache2-foreground
