#!/bin/bash
set -e

# Change memcached server.
sed -i "s|@MEMCACHED_SERVER@|$MEMCACHED_SERVER|" \
    /var/www/web/sites/default/settings.php

# Set the trusted host with www as subdomain.
sed -i "s|@WWWDOMAINNAME@|$WWWDOMAINNAME|" \
    /var/www/web/sites/default/settings.php

# Set the trusted host without any subdomain.
sed -i "s|@DOMAINNAME@|$DOMAINNAME|" \
    /var/www/web/sites/default/settings.php

# Just to make sure were at the root.
cd /var/www || return

# Insert the database settings into settings.php.
vendor/bin/drupal dba --password=$PASSWORD --driver=mysql --host=$HOST --database=$DB \
--username=$USERNAME --port=$PORT --default -n

if [ "$STARTUP" == 'drupal' ]; then

  # Start Apache.
  /usr/local/bin/apache2-foreground

elif [ "$STARTUP" == 'startup' ]; then

  # Update the database.
  vendor/bin/drush updb -y
  # Import configuration.
  vendor/bin/drush cim -y
  # Rebuild cache.
  vendor/bin/drush cr
fi
