palette:
  top: '#a79090'
  bottom: '#4e4e4e'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#976363'
  footer: '#161617'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#0073b6'
logo: 'public://color/bartik-de534313/logo.svg'
stylesheets:
  - 'public://color/bartik-de534313/colors.css'
files:
  - 'public://color/bartik-de534313/logo.svg'
  - 'public://color/bartik-de534313/colors.css'
