_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
langcode: en
uuid: 4179b8b2-88a2-4701-8068-53cc23be3062
name: ITOTKO
mail: info@itotko.dk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/7
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
